MZStaffPermissionCatalog = {
  { code = 'staff.panel.open', label = 'Abrir painel administrativo', group = 'painel' },
  { code = 'staff.roles.manage', label = 'Gerenciar cargos e atribuicoes Staff inferiores', group = 'staff' },
  { code = 'staff.coords.copy', label = 'Copiar coordenadas', group = 'movimento' },
  { code = 'staff.noclip', label = 'Usar noclip', group = 'movimento' },
  { code = 'staff.wall', label = 'Usar wall administrativo', group = 'observacao' },
  { code = 'staff.spectate', label = 'Espectar player inferior', group = 'observacao' },
  { code = 'staff.teleport', label = 'Teleportar por coordenadas ou waypoint', group = 'movimento' },
  { code = 'staff.players.list', label = 'Listar players online', group = 'players' },
  { code = 'staff.players.goto', label = 'Ir ate um player', group = 'players' },
  { code = 'staff.players.bring', label = 'Trazer um player', group = 'players' },
  { code = 'staff.players.kick', label = 'Remover player da sessao', group = 'players' },
  { code = 'staff.players.ban', label = 'Banir player online inferior', group = 'players' },
  { code = 'staff.bans.view', label = 'Consultar banimentos', group = 'banimentos' },
  { code = 'staff.bans.revoke', label = 'Revogar banimentos', group = 'banimentos' },
  { code = 'staff.whitelist.view', label = 'Consultar whitelist', group = 'whitelist' },
  { code = 'staff.whitelist.manage', label = 'Aprovar, recusar e revogar whitelist', group = 'whitelist' },
  { code = 'staff.warns.view', label = 'Consultar advertencias', group = 'advertencias' },
  { code = 'staff.warns.issue', label = 'Aplicar advertencias', group = 'advertencias' },
  { code = 'staff.warns.revoke', label = 'Revogar advertencias', group = 'advertencias' },
  { code = 'staff.players.heal', label = 'Curar player', group = 'players' },
  { code = 'staff.players.revive', label = 'Reviver player', group = 'players' },
  { code = 'staff.players.armor', label = 'Aplicar colete em si', group = 'players' },
  { code = 'staff.players.godmode', label = 'Alternar godmode em si', group = 'players' },
  { code = 'staff.vehicles.spawn', label = 'Criar veiculo administrativo temporario', group = 'veiculos' },
  { code = 'staff.vehicles.repair', label = 'Reparar veiculo', group = 'veiculos' },
  { code = 'staff.vehicles.delete', label = 'Remover entidade veicular', group = 'veiculos' },
  { code = 'staff.weapons.give', label = 'Dar arma nativa de teste', group = 'armas' },
  { code = 'staff.weapons.kit', label = 'Dar kit de armas nativas de teste', group = 'armas' },
  { code = 'staff.weapons.clear', label = 'Remover armas nativas de teste', group = 'armas' },
  { code = 'staff.garages.view', label = 'Visualizar garagens', group = 'garagens' },
  { code = 'staff.garages.create', label = 'Criar garagens', group = 'garagens' },
  { code = 'staff.garages.manage', label = 'Gerenciar garagens', group = 'garagens' },
  { code = 'staff.world.view', label = 'Visualizar definicoes do mundo', group = 'mundo' },
  { code = 'staff.world.doors.create', label = 'Criar portas persistentes', group = 'mundo' },
  { code = 'staff.world.doors.manage', label = 'Gerenciar portas persistentes', group = 'mundo' },
  { code = 'staff.world.doors.archive', label = 'Arquivar portas persistentes', group = 'mundo' },
  { code = 'staff.world.props.create', label = 'Criar props persistentes', group = 'mundo' },
  { code = 'staff.world.props.manage', label = 'Gerenciar props persistentes', group = 'mundo' },
  { code = 'staff.world.props.archive', label = 'Arquivar props persistentes', group = 'mundo' },
  { code = 'staff.orgs.view', label = 'Visualizar organizacoes', group = 'organizacoes' },
  { code = 'staff.orgs.create', label = 'Criar organizacoes', group = 'organizacoes' },
  { code = 'staff.orgs.edit', label = 'Editar organizacoes', group = 'organizacoes' },
  { code = 'staff.orgs.manage', label = 'Gerenciar cargos organizacionais', group = 'organizacoes' },
  { code = 'staff.orgs.archive', label = 'Arquivar organizacoes', group = 'organizacoes' },
  { code = 'staff.orgs.restore', label = 'Restaurar organizacoes', group = 'organizacoes' },
  { code = 'staff.orgs.features', label = 'Configurar features', group = 'organizacoes' },
  { code = 'staff.orgs.appearance', label = 'Configurar aparencia', group = 'organizacoes' },
  { code = 'staff.orgs.duty', label = 'Configurar pontos de servico', group = 'organizacoes' },
  { code = 'staff.orgs.set_leader', label = 'Definir lideranca', group = 'organizacoes' },
  { code = 'staff.members.invite', label = 'Adicionar membros', group = 'membros' },
  { code = 'staff.members.remove', label = 'Remover membros', group = 'membros' },
  { code = 'staff.members.promote', label = 'Promover membros', group = 'membros' },
  { code = 'staff.members.demote', label = 'Rebaixar membros', group = 'membros' },
  { code = 'staff.logs.view', label = 'Visualizar logs globais', group = 'logs' }
}

MZStaffPermissionSet = {}
for _, definition in ipairs(MZStaffPermissionCatalog) do
  MZStaffPermissionSet[definition.code] = true
end
